# Generated by Django 2.1.7 on 2019-03-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('faculty_name', models.CharField(max_length=50)),
                ('subject_knowledge', models.IntegerField()),
                ('pratical_knowledge', models.IntegerField()),
                ('class_maintainance', models.IntegerField()),
                ('branch_name', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
