# Generated by Django 2.1.7 on 2019-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190307_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
