# Generated by Django 2.1.7 on 2019-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_report_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
    ]
