# Generated by Django 2.1.7 on 2019-03-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190309_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_username', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_knowledge', models.IntegerField()),
                ('pratical_knowledge', models.IntegerField()),
                ('class_maintainance', models.IntegerField()),
                ('f_username', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
