# Generated by Django 2.1.7 on 2019-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190310_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('s_branch', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='subjectcode',
            fields=[
                ('s_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='subjectname',
            fields=[
                ('s_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
