# Generated by Django 2.1.7 on 2019-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_branch_subjectcode_subjectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectname',
            old_name='s_code',
            new_name='s_name',
        ),
    ]
