# Generated by Django 2.1.7 on 2019-03-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190329_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branch',
            new_name='branchh',
        ),
    ]
